### ISSUE TITLE
Having problem using any link from TawkTube ?!

### ISSUE THREAD

**Issue by ZoharML** [meoyawn/TawkTube#34]
Hi,
I’m using your tool for some time now with one link and it worked fine using both MusicBee and PocketCasts.
Lately it stopped playing.

Today I tried to add both new youtube playlists and the old one but none of them work.

For example:
When trying to add https://www.youtube.com/playlist?list=PLrxx1RzoWiyyfhkk84Vkz6XYaLrY6HMdDA
I get the link http://tawktube.com/playlist?list=PLrxx1RzoWiyyfhkk84Vkz6XYaLrY6HMdDA
While adding it to PocketCast (web interface) I get an error: “unable to find a podcast at this URL”
In MusicBee I get an error “unable to verify the validity of the URL”

When trying to play the list that was added in the past http://tawktube.com/playlist?list=PLx4jClAH_07w9JXxiCweGZz-RHG9BV5eQ
In PocketCast (web interface) I get the error “Your browser is unable to play this episode. Its stream my be corrupt or unsupported”. MusicBee can play the all list as it downloaded them all in the past.

So what’s wrong?

Zohar

**Comment by adelnizamutdinov** [comment]
there's nothing in https://www.youtube.com/playlist?list=PLrxx1RzoWiyyfhkk84Vkz6XYaLrY6HMdDA

I'll fix tawktube to respond with 404 in the case of non-existing playlists. Thanks for reporting!
